Summons commit
Anisetobegan/ludundare pull request #2
Opened 2024-05-06 23:44 UTC by Anisetobegan

2024-05-07 23:07 UTC, morathias requested changes

2024-05-07 23:07 UTC, morathias commented on Assets/Scripts/ghostScript.cs
> +    bool state = false;
this should be an enum state

2024-05-10 00:35 UTC, Anisetobegan commented on Assets/Scripts/ghostScript.cs
> +    bool state = false;
Done

2024-05-10 00:48 UTC, morathias approved these changes

2024-05-10 00:48 UTC, merged