Select summons
Anisetobegan/ludundare pull request #3
Opened 2024-05-23 23:46 UTC by Anisetobegan

2024-05-24 00:09 UTC, morathias requested changes

2024-05-24 00:09 UTC, morathias commented on Assets/Scripts/Character.cs
> +    public LayerMask ground;
Make LayerMask variables private serialized field

2024-05-24 00:09 UTC, morathias commented on Assets/Scripts/Character.cs
> +            Debug.Log("giving order");
Remove Debug

2024-05-24 00:09 UTC, morathias commented on Assets/Scripts/Character.cs
> +                    Debug.Log(hit.point);
Here as well

2024-05-27 00:16 UTC, Anisetobegan commented on Assets/Scripts/Character.cs
> +    public LayerMask ground;
Done

2024-05-27 00:16 UTC, Anisetobegan commented on Assets/Scripts/Character.cs
> +            Debug.Log("giving order");
Done

2024-05-27 00:16 UTC, Anisetobegan commented on Assets/Scripts/Character.cs
> +                    Debug.Log(hit.point);
Done

2024-05-27 00:51 UTC, morathias approved these changes

2024-05-27 00:51 UTC, merged